version: '3.5'

networks:
  whmcs:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes:
      - ${WHMCS_PATH}:${WHMCS_PATH_DOCKER}
      - ./nginx/templates:/etc/nginx/templates
      - ./.data/logs-nginx/:/var/log/nginx
    ports:
      - ${NGINX_PORT_HTTP}:80
    depends_on:
      - php-fpm
    networks:
      - whmcs
    environment:
      WHMCS_PATH_DOCKER: ${WHMCS_PATH_DOCKER}
      WHMCS_PATH_URL: ${WHMCS_PATH_URL}

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: ${PHP_VERSION}.Dockerfile
    volumes:
      - ${WHMCS_PATH}:${WHMCS_PATH_DOCKER}
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=xwhmcs
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - whmcs

  mysql:
    build:
      context: ./mysql
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - whmcs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
    networks:
      - whmcs

  # maildev:
  #   build: ./maildev
  #   ports:
  #     - "${MAILDEV_HTTP_PORT}:80"
  #     - "${MAILDEV_SMTP_PORT}:25"
  #   networks:
  #     - whmcs
